name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.0)'
        required: true
      type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Prisma client
        run: npm run prisma:generate
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
      
      - name: Update version
        run: npm version ${{ github.event.inputs.type }} --no-git-tag-version
      
      - name: Get version from package.json
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
      - name: Update CHANGELOG.md
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          DATE=$(date +%Y-%m-%d)
          
          # Add new version to CHANGELOG.md
          sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [$VERSION] - $DATE/" CHANGELOG.md
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Release version ${{ steps.package-version.outputs.version }}"
          title: "Release version ${{ steps.package-version.outputs.version }}"
          body: "Generated release PR for version ${{ steps.package-version.outputs.version }}"
          branch: "release/${{ steps.package-version.outputs.version }}"
